# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.13.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.13.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/yuntianwan/Documents/CPSC436D-GAME/game/minos-monster-maze

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/yuntianwan/Documents/CPSC436D-GAME/game/minos-monster-maze

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.13.2/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.13.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/yuntianwan/Documents/CPSC436D-GAME/game/minos-monster-maze/CMakeFiles /Users/yuntianwan/Documents/CPSC436D-GAME/game/minos-monster-maze/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/yuntianwan/Documents/CPSC436D-GAME/game/minos-monster-maze/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named 436d

# Build rule for target.
436d: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 436d
.PHONY : 436d

# fast build rule for target.
436d/fast:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/build
.PHONY : 436d/fast

src/a1.o: src/a1.cpp.o

.PHONY : src/a1.o

# target to build an object file
src/a1.cpp.o:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/a1.cpp.o
.PHONY : src/a1.cpp.o

src/a1.i: src/a1.cpp.i

.PHONY : src/a1.i

# target to preprocess a source file
src/a1.cpp.i:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/a1.cpp.i
.PHONY : src/a1.cpp.i

src/a1.s: src/a1.cpp.s

.PHONY : src/a1.s

# target to generate assembly for a file
src/a1.cpp.s:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/a1.cpp.s
.PHONY : src/a1.cpp.s

src/characters/character.o: src/characters/character.cpp.o

.PHONY : src/characters/character.o

# target to build an object file
src/characters/character.cpp.o:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/characters/character.cpp.o
.PHONY : src/characters/character.cpp.o

src/characters/character.i: src/characters/character.cpp.i

.PHONY : src/characters/character.i

# target to preprocess a source file
src/characters/character.cpp.i:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/characters/character.cpp.i
.PHONY : src/characters/character.cpp.i

src/characters/character.s: src/characters/character.cpp.s

.PHONY : src/characters/character.s

# target to generate assembly for a file
src/characters/character.cpp.s:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/characters/character.cpp.s
.PHONY : src/characters/character.cpp.s

src/characters/enemy.o: src/characters/enemy.cpp.o

.PHONY : src/characters/enemy.o

# target to build an object file
src/characters/enemy.cpp.o:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/characters/enemy.cpp.o
.PHONY : src/characters/enemy.cpp.o

src/characters/enemy.i: src/characters/enemy.cpp.i

.PHONY : src/characters/enemy.i

# target to preprocess a source file
src/characters/enemy.cpp.i:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/characters/enemy.cpp.i
.PHONY : src/characters/enemy.cpp.i

src/characters/enemy.s: src/characters/enemy.cpp.s

.PHONY : src/characters/enemy.s

# target to generate assembly for a file
src/characters/enemy.cpp.s:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/characters/enemy.cpp.s
.PHONY : src/characters/enemy.cpp.s

src/characters/fish.o: src/characters/fish.cpp.o

.PHONY : src/characters/fish.o

# target to build an object file
src/characters/fish.cpp.o:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/characters/fish.cpp.o
.PHONY : src/characters/fish.cpp.o

src/characters/fish.i: src/characters/fish.cpp.i

.PHONY : src/characters/fish.i

# target to preprocess a source file
src/characters/fish.cpp.i:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/characters/fish.cpp.i
.PHONY : src/characters/fish.cpp.i

src/characters/fish.s: src/characters/fish.cpp.s

.PHONY : src/characters/fish.s

# target to generate assembly for a file
src/characters/fish.cpp.s:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/characters/fish.cpp.s
.PHONY : src/characters/fish.cpp.s

src/characters/player.o: src/characters/player.cpp.o

.PHONY : src/characters/player.o

# target to build an object file
src/characters/player.cpp.o:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/characters/player.cpp.o
.PHONY : src/characters/player.cpp.o

src/characters/player.i: src/characters/player.cpp.i

.PHONY : src/characters/player.i

# target to preprocess a source file
src/characters/player.cpp.i:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/characters/player.cpp.i
.PHONY : src/characters/player.cpp.i

src/characters/player.s: src/characters/player.cpp.s

.PHONY : src/characters/player.s

# target to generate assembly for a file
src/characters/player.cpp.s:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/characters/player.cpp.s
.PHONY : src/characters/player.cpp.s

src/characters/salmon.o: src/characters/salmon.cpp.o

.PHONY : src/characters/salmon.o

# target to build an object file
src/characters/salmon.cpp.o:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/characters/salmon.cpp.o
.PHONY : src/characters/salmon.cpp.o

src/characters/salmon.i: src/characters/salmon.cpp.i

.PHONY : src/characters/salmon.i

# target to preprocess a source file
src/characters/salmon.cpp.i:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/characters/salmon.cpp.i
.PHONY : src/characters/salmon.cpp.i

src/characters/salmon.s: src/characters/salmon.cpp.s

.PHONY : src/characters/salmon.s

# target to generate assembly for a file
src/characters/salmon.cpp.s:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/characters/salmon.cpp.s
.PHONY : src/characters/salmon.cpp.s

src/characters/simple.o: src/characters/simple.cpp.o

.PHONY : src/characters/simple.o

# target to build an object file
src/characters/simple.cpp.o:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/characters/simple.cpp.o
.PHONY : src/characters/simple.cpp.o

src/characters/simple.i: src/characters/simple.cpp.i

.PHONY : src/characters/simple.i

# target to preprocess a source file
src/characters/simple.cpp.i:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/characters/simple.cpp.i
.PHONY : src/characters/simple.cpp.i

src/characters/simple.s: src/characters/simple.cpp.s

.PHONY : src/characters/simple.s

# target to generate assembly for a file
src/characters/simple.cpp.s:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/characters/simple.cpp.s
.PHONY : src/characters/simple.cpp.s

src/characters/smart.o: src/characters/smart.cpp.o

.PHONY : src/characters/smart.o

# target to build an object file
src/characters/smart.cpp.o:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/characters/smart.cpp.o
.PHONY : src/characters/smart.cpp.o

src/characters/smart.i: src/characters/smart.cpp.i

.PHONY : src/characters/smart.i

# target to preprocess a source file
src/characters/smart.cpp.i:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/characters/smart.cpp.i
.PHONY : src/characters/smart.cpp.i

src/characters/smart.s: src/characters/smart.cpp.s

.PHONY : src/characters/smart.s

# target to generate assembly for a file
src/characters/smart.cpp.s:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/characters/smart.cpp.s
.PHONY : src/characters/smart.cpp.s

src/characters/turtle.o: src/characters/turtle.cpp.o

.PHONY : src/characters/turtle.o

# target to build an object file
src/characters/turtle.cpp.o:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/characters/turtle.cpp.o
.PHONY : src/characters/turtle.cpp.o

src/characters/turtle.i: src/characters/turtle.cpp.i

.PHONY : src/characters/turtle.i

# target to preprocess a source file
src/characters/turtle.cpp.i:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/characters/turtle.cpp.i
.PHONY : src/characters/turtle.cpp.i

src/characters/turtle.s: src/characters/turtle.cpp.s

.PHONY : src/characters/turtle.s

# target to generate assembly for a file
src/characters/turtle.cpp.s:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/characters/turtle.cpp.s
.PHONY : src/characters/turtle.cpp.s

src/common.o: src/common.cpp.o

.PHONY : src/common.o

# target to build an object file
src/common.cpp.o:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/common.cpp.o
.PHONY : src/common.cpp.o

src/common.i: src/common.cpp.i

.PHONY : src/common.i

# target to preprocess a source file
src/common.cpp.i:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/common.cpp.i
.PHONY : src/common.cpp.i

src/common.s: src/common.cpp.s

.PHONY : src/common.s

# target to generate assembly for a file
src/common.cpp.s:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/common.cpp.s
.PHONY : src/common.cpp.s

src/gameAI.o: src/gameAI.cpp.o

.PHONY : src/gameAI.o

# target to build an object file
src/gameAI.cpp.o:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/gameAI.cpp.o
.PHONY : src/gameAI.cpp.o

src/gameAI.i: src/gameAI.cpp.i

.PHONY : src/gameAI.i

# target to preprocess a source file
src/gameAI.cpp.i:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/gameAI.cpp.i
.PHONY : src/gameAI.cpp.i

src/gameAI.s: src/gameAI.cpp.s

.PHONY : src/gameAI.s

# target to generate assembly for a file
src/gameAI.cpp.s:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/gameAI.cpp.s
.PHONY : src/gameAI.cpp.s

src/mazeComponents/fixedComponent.o: src/mazeComponents/fixedComponent.cpp.o

.PHONY : src/mazeComponents/fixedComponent.o

# target to build an object file
src/mazeComponents/fixedComponent.cpp.o:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/mazeComponents/fixedComponent.cpp.o
.PHONY : src/mazeComponents/fixedComponent.cpp.o

src/mazeComponents/fixedComponent.i: src/mazeComponents/fixedComponent.cpp.i

.PHONY : src/mazeComponents/fixedComponent.i

# target to preprocess a source file
src/mazeComponents/fixedComponent.cpp.i:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/mazeComponents/fixedComponent.cpp.i
.PHONY : src/mazeComponents/fixedComponent.cpp.i

src/mazeComponents/fixedComponent.s: src/mazeComponents/fixedComponent.cpp.s

.PHONY : src/mazeComponents/fixedComponent.s

# target to generate assembly for a file
src/mazeComponents/fixedComponent.cpp.s:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/mazeComponents/fixedComponent.cpp.s
.PHONY : src/mazeComponents/fixedComponent.cpp.s

src/mazeComponents/freeComponent.o: src/mazeComponents/freeComponent.cpp.o

.PHONY : src/mazeComponents/freeComponent.o

# target to build an object file
src/mazeComponents/freeComponent.cpp.o:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/mazeComponents/freeComponent.cpp.o
.PHONY : src/mazeComponents/freeComponent.cpp.o

src/mazeComponents/freeComponent.i: src/mazeComponents/freeComponent.cpp.i

.PHONY : src/mazeComponents/freeComponent.i

# target to preprocess a source file
src/mazeComponents/freeComponent.cpp.i:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/mazeComponents/freeComponent.cpp.i
.PHONY : src/mazeComponents/freeComponent.cpp.i

src/mazeComponents/freeComponent.s: src/mazeComponents/freeComponent.cpp.s

.PHONY : src/mazeComponents/freeComponent.s

# target to generate assembly for a file
src/mazeComponents/freeComponent.cpp.s:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/mazeComponents/freeComponent.cpp.s
.PHONY : src/mazeComponents/freeComponent.cpp.s

src/mazeComponents/mazeComponent.o: src/mazeComponents/mazeComponent.cpp.o

.PHONY : src/mazeComponents/mazeComponent.o

# target to build an object file
src/mazeComponents/mazeComponent.cpp.o:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/mazeComponents/mazeComponent.cpp.o
.PHONY : src/mazeComponents/mazeComponent.cpp.o

src/mazeComponents/mazeComponent.i: src/mazeComponents/mazeComponent.cpp.i

.PHONY : src/mazeComponents/mazeComponent.i

# target to preprocess a source file
src/mazeComponents/mazeComponent.cpp.i:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/mazeComponents/mazeComponent.cpp.i
.PHONY : src/mazeComponents/mazeComponent.cpp.i

src/mazeComponents/mazeComponent.s: src/mazeComponents/mazeComponent.cpp.s

.PHONY : src/mazeComponents/mazeComponent.s

# target to generate assembly for a file
src/mazeComponents/mazeComponent.cpp.s:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/mazeComponents/mazeComponent.cpp.s
.PHONY : src/mazeComponents/mazeComponent.cpp.s

src/physics.o: src/physics.cpp.o

.PHONY : src/physics.o

# target to build an object file
src/physics.cpp.o:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/physics.cpp.o
.PHONY : src/physics.cpp.o

src/physics.i: src/physics.cpp.i

.PHONY : src/physics.i

# target to preprocess a source file
src/physics.cpp.i:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/physics.cpp.i
.PHONY : src/physics.cpp.i

src/physics.s: src/physics.cpp.s

.PHONY : src/physics.s

# target to generate assembly for a file
src/physics.cpp.s:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/physics.cpp.s
.PHONY : src/physics.cpp.s

src/water.o: src/water.cpp.o

.PHONY : src/water.o

# target to build an object file
src/water.cpp.o:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/water.cpp.o
.PHONY : src/water.cpp.o

src/water.i: src/water.cpp.i

.PHONY : src/water.i

# target to preprocess a source file
src/water.cpp.i:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/water.cpp.i
.PHONY : src/water.cpp.i

src/water.s: src/water.cpp.s

.PHONY : src/water.s

# target to generate assembly for a file
src/water.cpp.s:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/water.cpp.s
.PHONY : src/water.cpp.s

src/world.o: src/world.cpp.o

.PHONY : src/world.o

# target to build an object file
src/world.cpp.o:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/world.cpp.o
.PHONY : src/world.cpp.o

src/world.i: src/world.cpp.i

.PHONY : src/world.i

# target to preprocess a source file
src/world.cpp.i:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/world.cpp.i
.PHONY : src/world.cpp.i

src/world.s: src/world.cpp.s

.PHONY : src/world.s

# target to generate assembly for a file
src/world.cpp.s:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/world.cpp.s
.PHONY : src/world.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... 436d"
	@echo "... src/a1.o"
	@echo "... src/a1.i"
	@echo "... src/a1.s"
	@echo "... src/characters/character.o"
	@echo "... src/characters/character.i"
	@echo "... src/characters/character.s"
	@echo "... src/characters/enemy.o"
	@echo "... src/characters/enemy.i"
	@echo "... src/characters/enemy.s"
	@echo "... src/characters/fish.o"
	@echo "... src/characters/fish.i"
	@echo "... src/characters/fish.s"
	@echo "... src/characters/player.o"
	@echo "... src/characters/player.i"
	@echo "... src/characters/player.s"
	@echo "... src/characters/salmon.o"
	@echo "... src/characters/salmon.i"
	@echo "... src/characters/salmon.s"
	@echo "... src/characters/simple.o"
	@echo "... src/characters/simple.i"
	@echo "... src/characters/simple.s"
	@echo "... src/characters/smart.o"
	@echo "... src/characters/smart.i"
	@echo "... src/characters/smart.s"
	@echo "... src/characters/turtle.o"
	@echo "... src/characters/turtle.i"
	@echo "... src/characters/turtle.s"
	@echo "... src/common.o"
	@echo "... src/common.i"
	@echo "... src/common.s"
	@echo "... src/gameAI.o"
	@echo "... src/gameAI.i"
	@echo "... src/gameAI.s"
	@echo "... src/mazeComponents/fixedComponent.o"
	@echo "... src/mazeComponents/fixedComponent.i"
	@echo "... src/mazeComponents/fixedComponent.s"
	@echo "... src/mazeComponents/freeComponent.o"
	@echo "... src/mazeComponents/freeComponent.i"
	@echo "... src/mazeComponents/freeComponent.s"
	@echo "... src/mazeComponents/mazeComponent.o"
	@echo "... src/mazeComponents/mazeComponent.i"
	@echo "... src/mazeComponents/mazeComponent.s"
	@echo "... src/physics.o"
	@echo "... src/physics.i"
	@echo "... src/physics.s"
	@echo "... src/water.o"
	@echo "... src/water.i"
	@echo "... src/water.s"
	@echo "... src/world.o"
	@echo "... src/world.i"
	@echo "... src/world.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

